---
# Ansible Galaxy requirements file
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  # Required for cluster and datacenter operations
  # Modules: cluster, cluster_drs, cluster_ha, cluster_vcls, cluster_info
  - name: vmware.vmware
    version: ">=1.11.0"

  # Required for guest/host operations and datacenter management
  # Modules: vmware_guest, vmware_host, vmware_datacenter, vmware_host_datastore, etc.
  - name: community.vmware
    version: ">=5.0.0"

  # Required for general utilities
  # Modules: iso_extract, timezone, etc.
  - name: community.general
    version: ">=5.0.0"
