---
# Ansible Galaxy requirements file
# Install with: ansible-galaxy collection install -r requirements.yml
# Upgrade existing: ansible-galaxy collection install -r requirements.yml --upgrade

collections:
  # Required for cluster and datacenter operations
  # Modules: cluster, cluster_drs, cluster_ha, cluster_vcls, cluster_info
  # Latest: 2.7.0+ (better support for Ansible 2.18+)
  - name: vmware.vmware
    version: ">=2.7.0"

  # Required for guest/host operations and datacenter management
  # Modules: vmware_guest, vmware_host, vmware_datacenter, vmware_host_datastore, etc.
  # Latest: 6.2.0+ (better support for Ansible 2.18+)
  - name: community.vmware
    version: ">=6.0.0"

  # Required for general utilities
  # Modules: iso_extract, timezone, etc.
  - name: community.general
    version: ">=11.0.0"
